# Generated by Django 5.2 on 2025-04-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_u3',
        ),
    ]
